# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarEventApp' do
  pod 'Google/SignIn'
  pod 'SlideMenuControllerSwift'
  use_frameworks!

  # Pods for CarEventApp

end
